//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsService1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Claim
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Claim()
        {
            this.OverPayments = new HashSet<OverPayment>();
        }
    
        public string ClaimNumber { get; set; }
        public decimal ClaimAmt { get; set; }
        public long MemberID { get; set; }
        public bool IsOverPayment { get; set; }
        public System.DateTime SysSrcSyncDate { get; set; }
    
        public virtual Member Member { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OverPayment> OverPayments { get; set; }
    }
}
