//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsService1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OverpaymentDBModelContainer1 : DbContext
    {
        public OverpaymentDBModelContainer1()
            : base("name=OverpaymentDBModelContainer1")
        {
            
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<OverPayment> OverPayments { get; set; }
        public virtual DbSet<Member> Members { get; set; }
        public virtual DbSet<Claim> Claims { get; set; }
    }
}
